apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-mysql
  labels:
    app: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-deployment-mysql
  template:
    metadata:
      labels:
        app: nginx-deployment-mysql
    spec:
      containers:
        - name: mysql
          image: nginx:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: root
